stages:
  - build-and-test
  - deploy

run-tests:
  stage: build-and-test
  cache:
    - key:
        files:
          - Cargo.toml
          - Cargo.lock
      paths:
        - ~/.cargo/bin/
        - ~/.cargo/registry/index/
        - ~/.cargo/registry/cache/
        - ~/.cargo/git/db/
        - target/
  parallel:
    matrix:
      - RUST_VERSION:
          - stable
          - beta
          - nightly
        TAGS:
          - saas-windows-medium-amd64
          - saas-linux-medium-amd64
  image: rust:latest
  tags: [$TAGS]
  script:
    - rustup update $RUST_VERSION
    - rustup default $RUST_VERSION
    - cargo build --verbose
    - cargo test --verbose

docs:
  stage: deploy
  cache:
    - key:
        files:
          - Cargo.toml
          - Cargo.lock
      paths:
        - ~/.cargo/bin/
        - ~/.cargo/registry/index/
        - ~/.cargo/registry/cache/
        - ~/.cargo/git/db/
        - target/
  image: rust:latest
  tags:
    - saas-linux-medium-amd64
  script:
    - cargo build --verbose
    - cargo test --verbose
    - cargo run --example build-book
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  allow_failure: true
