stages:
  - build-and-test
  - deploy

run-tests:
  stage: build-and-test
  parallel:
    matrix:
      - RUST_VERSION:
          - stable
          - beta
          - nightly
        TAGS:
          - saas-windows-medium-amd64
          - saas-linux-medium-amd64
  image: rust:latest
  tags: [$TAGS]
  script:
    - rustup update $RUST_VERSION
    - rustup default $RUST_VERSION
    - cargo build --verbose
    - cargo test --verbose

docs:
  stage: deploy
  image: rust:latest
  tags:
    - saas-linux-medium-amd64
  script:
    - cargo build --verbose
    - cargo test --verbose
    - cargo run --example build-book
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  allow_failure: true
