name: Build GitHub Pages

on:
  push:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        run: rustup update stable && rustup default stable

      - name: Cache Cargo files
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: book-bins-${{ runner.os }}-${{ github.sha }}
          restore-keys: book-bins-${{ runner.os }}-

      - name: Build the binary
        run: cargo run --example build-binary -- --verbose --current

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: bin-${{ matrix.os }}
          path: docs/src/

  build-book:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: bin-*
          path: docs/src/
          merge-multiple: true

      - name: Install Rust
        run: rustup update stable && rustup default stable

      - name: Restore Cargo files
        uses: actions/cache/restore@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: book-bins-${{ runner.os }}-${{ github.sha }}
          restore-keys: book-bins-${{ runner.os }}-

      - name: Cache built book
        uses: actions/cache@v4
        with:
          path: |
            docs/book/
          key: book-html-${{ github.sha }}
          restore-keys: book-html-

      - name: Build the book
        run: cargo run --example build-book

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/book/

  deploy:
    name: Deploy to GitHub Pages
    needs: build-book

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
